### ISSUE TITLE
Install Mermaid Extension

### ISSUE THREAD

**Issue by bequrios** [swiss/paf-link#17]
https://github.com/w3c/respec-mermaid

**Comment by bequrios** [comment]
the respec-mermaid extension apparently does not play well together with the markdown features of respec...

working example here: https://bequrios.github.io/mermaid and https://github.com/bequrios/mermaid

**Comment by l00mi** [comment]
Lets see if this https://stackoverflow.com/questions/49535327/change-mermaid-theme-in-markdown can help here.

**Comment by l00mi** [comment]
Asked about here: https://github.com/w3c/respec-mermaid/issues/9 No easy solution found for now.

**Comment by bequrios** [comment]
Solution is now available, see https://github.com/w3c/respec-mermaid/issues/9
