### ISSUE TITLE
Different naming of schema (Affairs vs. Affaires)

### ISSUE THREAD

**Issue by florihas** [swiss/paf-link#34]
Harmonize naming of schema: [Public Affairs](https://github.com/search?q=repo%3Aswiss%2Fpaf-link+%22public+affairs%22&type=code) Schema (vs. [Public Affair**e**s](https://github.com/search?q=repo%3Aswiss%2Fpaf-link+%22public+affaires%22&type=code) Schema)

**Comment by l00mi** [comment]
Thank you for the hint, should be solved now.
